server:
  port: 3000

spring:
  profiles:
    active: development # this is profile for logback

  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: postgres
    password: postgres

  jpa:
    hibernate:
          ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#debug: true
